"""empty message

Revision ID: 44649d46ad81
Revises: c3350947b2ac
Create Date: 2025-06-25 16:24:15.554104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44649d46ad81'
down_revision = 'c3350947b2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_record', schema=None) as batch_op:
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_record', schema=None) as batch_op:
        batch_op.alter_column('item',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('location_record')
    # ### end Alembic commands ###
