"""empty message

Revision ID: bacd264aa7ba
Revises: d55405a3a51d
Create Date: 2025-06-27 16:12:08.888915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacd264aa7ba'
down_revision = 'd55405a3a51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('led_sess_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('led_sess_record', schema=None) as batch_op:
        batch_op.drop_column('cumulative')

    # ### end Alembic commands ###
