"""add color

Revision ID: 021bbfc44b23
Revises: 82e986229973
Create Date: 2025-07-21 17:13:03.516877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021bbfc44b23'
down_revision = '82e986229973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False, server_default='#66ccff'))

    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('paypal_transaction_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.alter_column('paypal_transaction_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('bank_record', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
