"""Add created_at and last_login to User model

Revision ID: 145c3f52963f
Revises: 5a4c15715f6f
Create Date: 2025-07-16 18:08:31.879416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145c3f52963f'
down_revision = '5a4c15715f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
