"""add funding and vault to bankrecord

Revision ID: 1b82420a9d28
Revises: 021bbfc44b23
Create Date: 2025-07-21 17:34:20.876179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b82420a9d28'
down_revision = '021bbfc44b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_funding', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('is_vault', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_record', schema=None) as batch_op:
        batch_op.drop_column('is_vault')
        batch_op.drop_column('is_funding')

    # ### end Alembic commands ###
