"""Add game_preference to User model

Revision ID: 5a4c15715f6f
Revises: df4db11c22fd
Create Date: 2025-07-14 19:13:31.057874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4c15715f6f'
down_revision = 'df4db11c22fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_preference', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('game_preference')

    # ### end Alembic commands ###
