"""Add BlackjackSession table

Revision ID: df4db11c22fd
Revises: f494c0dfd467
Create Date: 2025-07-13 16:51:38.795131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4db11c22fd'
down_revision = 'f494c0dfd467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spread', sa.String(length=50), nullable=True),
    sa.Column('game_speed', sa.String(length=5), nullable=True),
    sa.Column('game_rules', sa.String(length=100), nullable=True),
    sa.Column('system', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session_record.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blackjack_session')
    # ### end Alembic commands ###
