"""Initialize session logs.

Revision ID: 26230f8c0f32
Revises: 
Create Date: 2025-06-16 19:18:10.887518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26230f8c0f32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('stakes', sa.String(length=50), nullable=True),
    sa.Column('time_in', sa.Time(), nullable=True),
    sa.Column('time_out', sa.Time(), nullable=True),
    sa.Column('money_in', sa.Float(), nullable=True),
    sa.Column('money_out', sa.Float(), nullable=True),
    sa.Column('comps_in', sa.Float(), nullable=True),
    sa.Column('comps_out', sa.Float(), nullable=True),
    sa.Column('tips', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_record')
    # ### end Alembic commands ###
